apiVersion: v1
kind: Service
metadata:
  name: nodeapp-load-balancer-service
spec:
  type: NodePort
  ports:
  - nodePort: 32410
    port: 80
    targetPort: 80
    Protocol: TCP
  selector:
    app: myapp
    type: front-end
