apiVersion: v1
kind: Service
metadata:
  name: nodeapp-NodePort-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      Protocol: TCP
  selector:
    app: myapp
    type: front-end
